id: 310a6843d1d14ca4b1abaca9c42d1ab2
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_155-The_Question_of_the_Naga_King-v1
  language: bo
  author: ''
  volume: {}
